# Generated by Django 3.2.9 on 2021-12-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profileform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileform',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='profileform',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profileform',
            name='update_on',
        ),
        migrations.AlterField(
            model_name='profileform',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
