# Generated by Django 3.2.9 on 2021-12-05 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20211205_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileform',
            name='user',
        ),
    ]
