# Generated by Django 3.2.9 on 2021-12-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_profileform_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='user',
        ),
    ]
