# Generated by Django 3.2.9 on 2021-12-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_is_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileform',
            name='photo',
        ),
        migrations.AddField(
            model_name='profileform',
            name='plateNo',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profileform',
            name='licence',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profileform',
            name='nidNo',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profileform',
            name='phoneNumber',
            field=models.IntegerField(max_length=50),
        ),
    ]
