# Generated by Django 3.2.9 on 2021-12-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20211227_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileform',
            name='vehicle',
            field=models.CharField(choices=[('one', 'Bike'), ('two', 'Car'), ('three', 'CNG')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profileform',
            name='licence',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profileform',
            name='nidNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profileform',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profileform',
            name='plateNo',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
