# Generated by Django 3.2.9 on 2021-12-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20211228_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileform',
            old_name='firstName',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='profileform',
            name='lastName',
        ),
        migrations.AlterField(
            model_name='profileform',
            name='vehicle',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
