# Generated by Django 3.2.9 on 2021-12-29 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20211228_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileform',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileform',
            name='plateNo',
            field=models.IntegerField(max_length=40, null=True),
        ),
    ]
