# Generated by Django 3.2.9 on 2021-12-29 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20211230_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profileform',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profileform',
            name='userName',
        ),
    ]
